const nodemailer = require("nodemailer");

export default async function POST(req, res) {
    try {
        const { name, email, pageUrl} = await req.body;
        const transporter = nodemailer.createTransport({
            service: "gmail",
            host: "smtp.gmail.com",
            port: 465,
            secure: true,
            auth: {
                user: 'lead@bookwritingexperts.com',
                pass: "10@Kskwoks"
            }
        })

        const mailOptions = {
            from: 'lead@bookwritingexperts.com',
            to: 'lead@bookwritingexperts.com',
            subject: `New Lead Generated By BookWritingExperts`,
            html: `<table>
               
                   <tr>
                        <th>Name</th>
                        <td>${name}</td>
                    </tr>

                    <tr>
                        <th>Email</th>
                        <td>${email}</td>
                    </tr>

                    <tr>
                    <th>pageUrl</th>
                    <td>${pageUrl}</td>
                </tr>
                   
               
               
                  
                
            </table>`
        }

        await transporter.sendMail(mailOptions);


        var currentdate = new Date().toLocaleString() + ''
        let headersList = {
            "Accept": "*/*",
            "User-Agent": "Thunder Client (https://www.thunderclient.com)",
            "Authorization": "Bearer ke2br2ubssi4l8mxswjjxohtd37nzexy042l2eer",
            "Content-Type": "application/json"
           }
           
           let bodyContent = JSON.stringify({
             "IP" :  req.headers['x-forwarded-for'] || req.connection.remoteAddress,
             "Brand": "BOOK-WRITING-EXPERT",
             "Page" : `${pageUrl}`,
             "Date" : currentdate,
             "Time" : currentdate,
             "JSON" : {
               "form" : {
                 "name" : `${name}`,
                 "email": `${email}`,
                 "pageURL":`${pageUrl}`
               } 
             }
           });
           
         await fetch("https://sheetdb.io/api/v1/1ownp6p7a9xpi", { 
             method: "POST",
             body: bodyContent,
             headers: headersList
           });

        return res.json({ "message": "Email send sucessfully", "data": [name, email, pageUrl], "status": 200 });
    } catch (error) {
        return res.json({ "message": "Failed to send Email", "data": error, "status": 500 });
    }
}