const nodemailer = require("nodemailer");

export default async function POST(req, res) {
    try {
        const { name, email, phone, message } = await req.body;
        const transporter = nodemailer.createTransport({
            service: "gmail",
            host: "smtp.gmail.com",
            port: 465,
            secure: true,
            auth: {
                user: 'signup@bitswits.com',
                pass: "10@Kskwoks"
            }
        })

        const mailOptions = {
            from: 'signup@bitswits.com',
            to: 'signup@bitswits.com',
            subject: `New Lead Generated By BitsWits`,
            html: `<table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Message</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>${name}</td>
                        <td>${email}</td>
                        <td>${phone}</td>
                        <td>${message}</td>
                    </tr>
                </tbody>
            </table>`
        }

        await transporter.sendMail(mailOptions);

        return res.json({ "message": "Email send sucessfully", "data": [name, email, phone, message], "status": 200 });
    } catch (error) {
        return res.json({ "message": "Failed to send Email", "data": error, "status": 500 });
    }
}